default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ["--maxkb", "16384"]

  # python code formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.0"
    hooks:
      - id: ruff-format
      - id: ruff-check
        args:
          [
            "--select",
            "D,E,F,W,I,S,UP",
            "--extend-ignore",
            "E402,E501,F401,F841,S101",
            "--exclude",
            "logs/*,data/*",
            "--fix",
            "--exit-non-zero-on-fix",
          ]
        types_or: [python, pyi, jupyter]

  # yaml formatting
  # - repo: https://github.com/google/yamlfmt
  #   rev: v0.17.
  #   hooks:
  #     - id: yamlfmt

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          # - mdformat-toc
          # - mdformat-black

  # jupyter notebook cell output clearing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args: ["--drop-empty-cells", "--keep-output"]
